### ISSUE TITLE
install broken, dns failure on download URL from digital ocean

### ISSUE THREAD

**Issue by nergdron** [caius/zed-make#10]
I can't install this extension today, zed logs show there's an error with the URL:

```
2024-11-28T18:00:35.20067278-08:00 [ERROR] error downloading extension: error sending request for url (https://zed-extensions.nyc3.digitaloceanspaces.com/extensions/make/1.0.1/archive.tar.gz?x-id=GetObject&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=DO0024BKKDAMB3MYP3DP%2F20241129%2Fnyc3%2Fs3%2Faws4_request&X-Amz-Date=20241129T020035Z&X-Amz-Expires=180&X-Amz-SignedHeaders=host&X-Amz-Signature=d9aa2b592deead818f1624a18df2a3780dfdb67c184aea272cec20be16009c72)
```

testing further, it looks like DNS for this hostname is failing, even going directly to the listed DNS servers from whois:

```
$ dig zed-extensions.nyc3.digitaloceanspaces.com @KIM.NS.CLOUDFLARE.COM                                                                           
; <<>> DiG 9.20.3 <<>> zed-extensions.nyc3.digitaloceanspaces.com @KIM.NS.CLOUDFLARE.COM
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17209
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;zed-extensions.nyc3.digitaloceanspaces.com. IN A

;; ANSWER SECTION:
zed-extensions.nyc3.digitaloceanspaces.com. 120	IN A 162.243.189.2

;; Query time: 3 msec
;; SERVER: 173.245.58.126#53(KIM.NS.CLOUDFLARE.COM) (UDP)
;; WHEN: Thu Nov 28 18:02:12 PST 2024
;; MSG SIZE  rcvd: 87
```

so you may need to check your hosting around where this data is mirrored.

**Comment by ohroy** [comment]
+1

**Comment by nergdron** [comment]
oh yeah, looks great, thanks!

**Comment by caius** [comment]
Thanks for reporting, looks like Zed have a mirror of the extensions they control rather than downloading for GitHub and that was failing to resolve. I don't have control of that, so would be unable to help if this recurs.

If you see similar errors again please raise it upstream on the Zed extensions repo issues rather than here https://github.com/zed-industries/extensions/issues

**Comment by caius** [comment]
> testing further, it looks like DNS for this hostname is failing, even going directly to the listed DNS servers from whois:
> 
> ```
> $ dig zed-extensions.nyc3.digitaloceanspaces.com @KIM.NS.CLOUDFLARE.COM                                                                           
> ; <<>> DiG 9.20.3 <<>> zed-extensions.nyc3.digitaloceanspaces.com @KIM.NS.CLOUDFLARE.COM
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17209
> ;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> ;; WARNING: recursion requested but not available
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;zed-extensions.nyc3.digitaloceanspaces.com. IN A
> 
> ;; ANSWER SECTION:
> zed-extensions.nyc3.digitaloceanspaces.com. 120	IN A 162.243.189.2
> 
> ;; Query time: 3 msec
> ;; SERVER: 173.245.58.126#53(KIM.NS.CLOUDFLARE.COM) (UDP)
> ;; WHEN: Thu Nov 28 18:02:12 PST 2024
> ;; MSG SIZE  rcvd: 87
> ```

For reference this appears to be resolving fine, you're getting an IP address back for the A record in the ANSWER SECTION - `162.243.189.2`.
