### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by caius** [caius/zed-make#2]
In theory this is just add languages/make/highlights.scm with the correct contents to make it highlight the tree-sitter parsed bits.

In practice trying this in #1 copying it from https://github.com/zed-industries/zed/pull/7402 it just crashes.

**Comment by larrysammii** [comment]
Hi @caius,

Not sure if syntax highlighting is already being implemented yet but please refer to my issue below.
[https://github.com/zed-industries/zed/issues/8518#issue-2158289478](url)

Thanks for your time!
